#!/bin/bash

# Obtener el nombre de la pantalla
display=$(xrandr | grep " connected" | awk '{ print$1 }')

# Obtener el valor actual del brillo
current_brightness=$(xrandr --verbose | grep -i brightness | cut -f2 -d ' ')

# Obtener el valor del incremento de brillo
increment=0.10


function subir {  
new_brightness=$(echo "$current_brightness + $increment" | bc)

# Establecer el nuevo valor del brillo
xrandr --output $display --brightness $new_brightness
}

function bajar {
new_brightness=$(echo "$current_brightness - $increment" | bc)

xrandr --output $display --brightness $new_brightness


}


perfil=$(echo "xrandr --output $display --brightness $current_brightness" >> .config/bspwm/brightness.txt)


# Scripts parameters

if  [[ $1 = "--subir" ]]; then
#sed '$d' /home/j/.config/bspwm/bspwmrc >> /home/j/.config/bspwm/bspwmrc
	subir
#	$perfil
#cat /home/j/.config/bspwm/brightness.txt | sed '$!d' >> /home/j/.config/bspwm/bspwmrc
	echo subio

elif  [[ $1 = "--bajar" ]]; then
	bajar
#	$perfil
    echo bajo
else
	
	cat <<- _EOF_
	No option specified, Available options:
	  --subir	--bajar 
	
	_EOF_
fi

exit 0 
